name: practice
description: Firebase with flutter

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.1
  firebase_core_platform_interface: 4.5.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/